In [1]:
#段落向量构建PVDM

In [2]:
#加载第三方库
import gensim
import smart_open
from gensim.models.doc2vec import TaggedDocument, Doc2Vec
from xlrd import open_workbook
import jieba

In [3]:
#加载数据
rb = open_workbook('/Users/mccat/PycharmProjects/PlaceDatasetCollectionTools/二次过滤模块/CPData1.0000.xls')
# 通过sheet_by_index()获取的sheet没有write()方法
rs = rb.sheet_by_index(0)

In [4]:
a = jieba.cut(rs.cell(1,1).value)

In [5]:
cut_list = [ i for i in a ]

Building prefix dict from the default dictionary ...
Loading model from cache /var/folders/d3/svrm6_zd5yd_6hjjkrp617d00000gn/T/jieba.cache
Loading model cost 0.851 seconds.
Prefix dict has been built succesfully.


In [6]:
rs.cell(1,1).value

'求吉林长春净月区的所有大学_百度知道'

In [7]:
cut_list

['求', '吉林长春', '净月区', '的', '所有', '大学', '_', '百度', '知道']

In [8]:
text_list=[]
text_lable = []

In [9]:
from gensim.models.doc2vec import Doc2Vec, TaggedDocument
from gensim.test.utils import get_tmpfile

In [10]:
TaggededDocument = gensim.models.doc2vec.TaggedDocument # 输入输出内容都为 词袋 + tag列表，

In [ ]:
def 
    for text in train_texts_orig:
    # 去掉标点
    text = re.sub("[\s+\.\!\/_,$%^*(+\"\']+|[+——！，。？、~@#￥%……&*（）]+ ", "",text)
    # 结巴分词
    cut = jieba.cut(text)
    # 结巴分词的输出结果为一个生成器
    # 把生成器转换为list
    cut_list = [ i for i in cut ]
    

In [24]:
for i in range(1,rs.nrows):
    st = str(rs.cell(i,1).value)+str(rs.cell(i,2).value)+str(rs.cell(i,4).value)+str(rs.cell(i,5).value)+str(rs.cell(i,6).value)
    
    jieba_list = jieba.cut(st)
    cut_list1 = [ j for j in jieba_list ]
#     text_list.append([str(rs.cell(i,1).value)])
#     text_lable.append(rs.cell(i,7).value)
    text_list.append(cut_list1)
    text_lable.append(rs.cell(i,7).value)
    if i == 1:
        print(st)

求吉林长春净月区的所有大学_百度知道最佳答案: 东北师范大学净月校区 东北师范大学人文学院 吉林农业大学 吉林公安高等专科学校 长春中医药大学 长春税务学院 吉林建筑工程学院净月校区 吉林华侨外国语学校 ...https://zhidao.baidu.com/quest... 求吉林长春净月区的所有大学_百度知道知道求吉林长春净月区的所有大学
求吉林长春净月区的所有大学
答题抽奖已赞过已踩过已赞过已踩过已赞过已踩过已赞过已踩过已赞过已踩过已赞过已踩过1为你推荐：其他类似问题
10

3

3

51

1

16

8

32
您可能关注的内容等你来答相关搜索 我来答经验宝宝知道作业帮

手机版


我的知道求吉林长春净月区的所有大学如题，只要净月区的怎么才能报在这些大学的净月校区？...
如题，只要净月区的怎么才能报在这些大学的净月校区？
 我来答首次认真答题后即可获得3次抽奖机会，100%中奖。3次100%可选中1个或多个下面的关键词，搜索相关资料。也可直接点“搜索资料”搜索整个问题。吉林长春大学
最佳答案
wanenoble知道合伙人

推荐于2017-11-21


推荐于2017-11-21
wanenoble采纳数：1616获赞数：100100LV4擅长：长春市
保险
度假旅游
家居装修





已赞过已踩过<评论收起gomilango知道合伙人

2009-06-18


2009-06-18
gomilango采纳数：1357813578获赞数：7429374293LV20擅长：交通出行





已赞过已踩过<评论收起tianzhouyuanna知道合伙人

2009-06-19


2009-06-19
tianzhouyuanna采纳数：110110获赞数：927927LV7擅长：长春市
吉林市
管理学





已赞过已踩过<评论收起小小lspring知道合伙人

2009-06-19


2009-06-19
小小lspring采纳数：5555获赞数：183183LV6擅长：暂未定制
暂未定制




已赞过已踩过<评论收起citigm知道合伙人

2009-06-19


2009-06-19
citigm采纳数：9999获赞数：323323LV6擅长：暂未定制
暂未定制




已赞过已踩过<评论收起mxl62

KeyboardInterrupt: 

In [14]:
from gensim.test.utils import common_texts

In [15]:
common_texts

[['human', 'interface', 'computer'],
 ['survey', 'user', 'computer', 'system', 'response', 'time'],
 ['eps', 'user', 'interface', 'system'],
 ['system', 'human', 'system', 'eps'],
 ['user', 'response', 'time'],
 ['trees'],
 ['graph', 'trees'],
 ['graph', 'minors', 'trees'],
 ['graph', 'minors', 'survey']]

In [16]:
type(common_texts)

list

In [23]:
text_list[0]
# rs.nrows

['求', '吉林长春', '净月区', '的', '所有', '大学', '_', '百度', '知道']

加载构建向量第三方库

In [94]:
# for label in  enumerate(text_lable)
# documents = [TaggedDocument(text_list[i], [rs.cell(i,7).value]) for i in range(1,4300)]
documents = [TaggedDocument(doc, [i]) for i, doc in enumerate(text_list)]
model = Doc2Vec(documents, vector_size=5, window=2, min_count=1, workers=4)
# model.train(text_list, total_examples=model.corpus_count, epochs=70)

In [95]:
type(documents)
documents[10]

TaggedDocument(words=['长春市', '实验', '中学', '净', '月', '学校', '_', '学', '-', '首页'], tags=[10])

In [96]:
#将模型保存
from gensim.test.utils import get_tmpfile

fname = get_tmpfile("my_doc2vec_model")

model.save(fname)
#加载模型
model = Doc2Vec.load(fname)

In [97]:
#已完成模型训练（=不再更新，仅查询，减少内存使用）
model.delete_temporary_training_data(keep_doctags_vectors=True, keep_inference=True)

In [98]:
model.infer_vector(['2018东北师范大学校园概况之净月校区-净月校区图文介绍-净月校区...'])

array([ 0.05332169, -0.05471705, -0.07858792, -0.03349514, -0.09630442],
      dtype=float32)

In [99]:
model.infer_vector(['2018东北师范大学学校情况之净月校区-净月校区图文介绍-净月校区...'])

array([ 0.07587329, -0.03501265, -0.08501966,  0.04046297,  0.05179763],
      dtype=float32)

In [100]:
model.infer_vector(['真不知道说什么'])

array([ 0.04539145,  0.08157185,  0.0507837 , -0.05943672, -0.00047193],
      dtype=float32)

In [101]:
#寻找与某个文档最相似的文档
model.docvecs.most_similar(100)

/Users/mccat/anaconda3/lib/python3.6/site-packages/gensim/matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):


[(3951, 0.9988572001457214),
 (2925, 0.9962765574455261),
 (3064, 0.9934536218643188),
 (3969, 0.9926314353942871),
 (2851, 0.9915133118629456),
 (2209, 0.9913701415061951),
 (684, 0.991215705871582),
 (590, 0.9907518625259399),
 (4070, 0.990214467048645),
 (3182, 0.9886208772659302)]

In [102]:
tests =[(3951, 0.9988572001457214),
 (2925, 0.9962765574455261),
 (3064, 0.9934536218643188),
 (3969, 0.9926314353942871),
 (2851, 0.9915133118629456),
 (2209, 0.9913701415061951),
 (684, 0.991215705871582),
 (590, 0.9907518625259399),
 (4070, 0.990214467048645),
 (3182, 0.9886208772659302)]
for test in tests:
    print(rs.cell(test[0],7))
print(rs.cell(100,7))

number:0.0
number:1.0
number:1.0
number:1.0
number:0.0
number:0.0
number:1.0
number:1.0
number:0.0
number:1.0
number:1.0


In [103]:
model.infer_vector(["吉林", "南关区"])

array([ 0.0195021 ,  0.10887525, -0.04643046,  0.07751875, -0.00699571],
      dtype=float32)